[package]
name = "uuid64rs"
version = "0.0.1"
description = "UUID v4 (random) Rust package with a custom base 64 encoding added."
authors = ["Michael Cummings <dragonrun1@gmail.com>"]
edition = "2018"

[dependencies]
